name: 🐞 Bug Report
description: File a bug report
title: "[🐞]: "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: Thank you for taking the time to fill out this bug report form!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the [issues](https://github.com/neatrealm/NeatPhysics.jl/issues) and found no similar bug reports
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    placeholder: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    placeholder: A concise description of what you expected to happen.
- type: textarea
  attributes:
    label: Possible Solution
    placeholder: A concise description of what you think.
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu v23.04
        - **Julia**: v1.0.0
        - **NeatPhysics.jl**: v1.0.0
    value: |
        - OS:
        - Julia:
        - NeatPhysics.jl:
    render: markdown
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    placeholder: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: textarea
  attributes:
    label: Anything else?
    description: Links? References? Anything that will give us more context about the issue you are encountering!
    placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
