name: docs-CI
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - docs/**
    tags: ['*']
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Configure doc environment
        run: |
          julia --project=docs/ -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using NeatPhysics
            DocMeta.setdocmeta!(NeatPhysics, :DocTestSetup, :(using NeatPhysics); recursive=true)
            doctest(NeatPhysics)'
